"use server";
import { revalidatePath } from "next/cache";
import { crearClienteSupabaseServidor } from "@/lib/supabase/server";
import { obtenerContextoAutorizado } from "@/features/autenticacion/servicio-autorizacion";
import { cambiarEstadoPaciente, crearPaciente, editarPaciente, eliminarPaciente, ErrorPacientes } from "./servicio-pacientes";
import type { EstadoPaciente } from "./tipos-pacientes";
export type EstadoPacienteAccion = { exito?: string; error?: string };
const datos = (f: FormData) => ({ nombreApellido: String(f.get("nombreApellido") ?? ""), documento: String(f.get("documento") ?? ""), telefono: String(f.get("telefono") ?? ""), codigoPais: String(f.get("codigoPais") ?? "+595"), sexo: String(f.get("sexo") ?? "") });
const mensajeError = (e: unknown, crear: string, editar: string) => e instanceof ErrorPacientes && e.codigo === "no_autorizado" ? `No tienes acceso a la actividad: ${crear}.` : e instanceof ErrorPacientes && e.codigo === "existente" ? "Ya existe un paciente con esa cédula." : e instanceof ErrorPacientes && e.codigo === "invalido" ? e.detalle ?? "Revisa los datos ingresados." : `No fue posible ${editar.toLowerCase()}.`;
export async function crearPacienteAccion(_: EstadoPacienteAccion, f: FormData) { try { const r = await crearPaciente(datos(f), await obtenerContextoAutorizado(await crearClienteSupabaseServidor())); revalidatePath("/pacientes"); return { exito: r === "reactivado" ? "Paciente reactivado correctamente." : "Paciente creado correctamente." }; } catch (e) { return { error: mensajeError(e, "Crear pacientes", "crear el paciente") }; } }
export async function editarPacienteAccion(_: EstadoPacienteAccion, f: FormData) { try { await editarPaciente(String(f.get("id") ?? ""), datos(f), await obtenerContextoAutorizado(await crearClienteSupabaseServidor())); revalidatePath("/pacientes"); return { exito: "Paciente actualizado correctamente." }; } catch (e) { return { error: mensajeError(e, "Editar pacientes", "editar el paciente") }; } }
export async function cambiarEstadoPacienteAccion(_: EstadoPacienteAccion, f: FormData) { try { await cambiarEstadoPaciente(String(f.get("id") ?? ""), String(f.get("estado") ?? "inactivo") as EstadoPaciente, await obtenerContextoAutorizado(await crearClienteSupabaseServidor())); revalidatePath("/pacientes"); return { exito: "Estado del paciente actualizado." }; } catch (e) { return { error: mensajeError(e, "Editar pacientes", "cambiar el estado") }; } }
export async function eliminarPacienteAccion(_: EstadoPacienteAccion, f: FormData) { try { await eliminarPaciente(String(f.get("id") ?? ""), await obtenerContextoAutorizado(await crearClienteSupabaseServidor())); revalidatePath("/pacientes"); return { exito: "Paciente eliminado correctamente." }; } catch (e) { return { error: e instanceof ErrorPacientes && e.codigo === "no_autorizado" ? "No tienes acceso a la actividad: Eliminar pacientes." : "No fue posible eliminar el paciente; puede tener turnos asociados." }; } }
